name: Daily Twitter Bot

on:
  schedule:
    - cron: "0 12 * * *"   # Her gün 12:00'da paylaşır
  workflow_dispatch:      # Elle çalıştırmak için buton ekler

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
      - name: Repo indiriliyor
        uses: actions/checkout@v3

      - name: Python kuruluyor
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Kütüphaneler
        run: pip install tweepy

      - name: Tweet at
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: python main.py
